Update richpager from upstream

diff --git a/bin/richpager b/bin/richpager
--- a/bin/richpager
+++ b/bin/richpager
@@ -1,134 +1,238 @@
 #!/bin/bash
-#
-# @(#) richpager ver.0.1 2014.10.2
-#
-# Usage:
-#   richpager file...
-#
-# Description:
-#   Rich pager; Cat or less automatically, with pygmentize.
-#
+
+set -e
+
+# Function to check whether a certain command
+# exists in the environment variable $PATH
+# Return zero(true) if present
 # Created by b4b4r07
-######################################################################
 
-function richpager()
+is_exists()
 {
-    # Use cat as default pager.
-    Pager='cat'
-    if type pygmentize >/dev/null 2>&1; then
-        Pager='pygmentize -O style=solarizeddark -f console256 -g'
-        get_styles="from pygments.styles import get_all_styles
-        styles = list(get_all_styles())
-        print '\n'.join(styles)"
-        styles=$(echo "$get_styles" | sed -e 's/^  *//g' | python)
+    [[ -n $1 ]] || return 1
+    type "$1" >/dev/null 2>&1
+    return $?
+}
+
+argc=0
+existent_files=()
+non_existent_files=()
+
+if is_exists 'python'; then
+    # Getting a list of available styles
+    #
+    # Because it could be that a plugin registered a style,
+    # there is a way to iterate over all styles:
+    #
+    get_styles="from pygments.styles import get_all_styles
+    styles = list(get_all_styles())
+    print '\n'.join(styles)"
+    # See also <http://pygments.org/docs/styles/>
+
+    # Getting a list of styles for shell script
+    # 'sed -e ...' indent the beginning of a line space for Python
+    styles=( $(echo "$get_styles" | sed -e 's/^  *//g' | python) )
+fi
+style='default'
+
+highlighter='cat'
+if is_exists 'pygmentize'; then
+    highlighter="pygmentize -O style=$style -f console256 -g 2>/dev/null"
+fi
+m_option=''
+
+args()
+{
+    # Err
+    # With no argument, return false
+    if [[ -z $1 ]]; then
+        echo "error: too few argument" 1>&2
+        return 1
     fi
-    Less='less -R +Gg'
-    # Get display lines.
-    DispLines=$(( $( stty 'size' < '/dev/tty' | cut -d' ' -f1 ) - 2 ))
 
-    declare -i arg=0
-    declare -a exist_files=()
-    declare -a non_exist_files=()
+    # In bash, this functions is the simplest way to test
+    # if an array($styles) contains a certain value.
+    # In case of this script,
+    # check if $styles array contains a certain($1) value
+    in_array()
+    {
+        local e
+        for e in "${styles[@]}"
+        do
+            [[ "$e" == "$1" ]] && return 0
+        done
+        return 1
+    }
 
-    while (( $# > 0 ))
+    #
+    # Before changing
+    #
+    # Set default color scheme
+    # use solarized if exists
+    if in_array 'solarized'; then
+        style='solarized'
+        highlighter="pygmentize -O style=$style -f console256 -g 2>/dev/null"
+    fi
+    local n_flag=''
+    local l_flag='-F'
+
+    #
+    # Do changing
+    #
+    while (($# > 0))
     do
         case "$1" in
             -*)
+                # help option:
                 if [[ "$1" =~ h ]]; then
-                    echo "usage: richpager [-h][-nlp] file..."
+                    echo "usage: richpager [-h][-nlp][-a] file..."
                     echo "  -h       Show this help"
                     echo "  -n       Number the output lines, starting at 1"
                     echo "  -l       Use less nevertheless linage"
                     echo "  -p       Use plane text without pygmentize"
                     echo "  -s style Specify the style for highlighting"
+                    echo "  -m       Display multiple files in multiple buffer"
                     return 0
                 fi
-                if [[ "$1" =~ n ]]; then
-                    nflag='-n'
-                fi
-                if [[ "$1" =~ l ]]; then
-                    lflag='-l'
-                fi
+
+                # -p switch:
+                # Plain test
+                # Do not do syntax highlighting
                 if [[ "$1" =~ p ]]; then
-                    pflag='-p'
+                    LESSOPEN=''
+                    highlighter='cat'
                 fi
+
+                # -n switch:
+                # Outputs with line number, starting at 1
+                if [[ "$1" =~ n ]]; then
+                    n_flag='-N'
+                fi
+
+                # -l switch:
+                # Use less unlike cat-like output
+                if [[ "$1" =~ l ]]; then
+                    l_flag=''
+                fi
+
+                # -m flag:
+                # When is is possible to use the pygmentize,
+                # to specify a color scheme for syntax highlighting
+                # If no argument is given,
+                # list all available color schemes
+                # e.g. $0 -s [style]
+                #      -s       -> list color schemes
+                #      -s style -> use style as a color scheme if available
                 if [[ "$1" =~ s ]]; then
-                    declare style="default"
-                    if echo "$styles" | grep -q -x "${2:-NONE}"; then
-                        style="$2"
-                        shift
+                    if ! is_exists 'python'; then
+                        echo "error: Can not get the list of style for the highlight" 1>&2
+                        return 1
                     fi
-                    Pager="pygmentize -O style=$style -f console256 -g"
+
+                    shift
+                    if [[ -z $1 ]]; then
+                        # If no arguments are given,
+                        # list all available styles
+                        local s
+                        for s in "${styles[@]}"
+                        do
+                            echo "$s"
+                        done
+                        return 1
+                    else
+                        # Set a style if the styles array contains a style specified by the user
+                        if is_exists 'pygmentize'; then
+                            if in_array "$1"; then
+                                style="$1"
+                            fi
+                            highlighter="pygmentize -O style=$style -f console256 -g 2>/dev/null"
+                        else
+                            echo "error: This -s option needs Pygments" 1>&2
+                            return 1
+                        fi
+                    fi
                 fi
+
+                # -m switch:
+                # If the file given as the argument is more,
+                # does not concatenate the text of the file,
+                # such as the cat command
+                if [[ "$1" =~ m ]]; then
+                    m_option=1
+                fi
+
+                # shift the switch and flags
+                # In the case of options that take an argument(that is flag),
+                # shift in the if statement to perform the argument processing
+                # e.g. -s option
                 shift
                 ;;
             *)
-                ((++arg))
-                if [ -e "$1" ]; then
-                    exist_files=("${exist_files[@]}" "$1")
+                # Describe later error raised for a file that does not exist
+                if [[ -f $1 ]]; then
+                    existent_files=("${existent_files[@]}" "$1")
                 else
-                    non_exist_files=("${non_exist_files[@]}" "$1")
+                    non_existent_files=("${non_existent_files[@]}" "$1")
                 fi
                 shift
                 ;;
         esac
     done
 
-    # Option -p
-    if [ -n "$pflag" ]; then
-        Pager='cat'
-    fi
-
     #
-    # Count the number of lines in the all files given as an argument
+    # After changing
     #
-    if [ -p /dev/stdin ] || (( arg < 1 )); then
-        File=$( cat - )
-        FileLines=$(echo -n "$File" | grep -c '')
-    elif (( arg > 0 )); then
-        declare -a lines=('0')
-        for file in "${exist_files[@]}"
-        do
-            lines+="+ $(wc -l <$file)"
-        done
-        FileLines=$(echo "${lines[@]} + ${#non_exist_files[@]}" | bc)
-    fi
+    argc="${#existent_files[@]}"
+    LESSOPEN="| ${highlighter} %s"
+    export LESSOPEN
 
-    #
-    # Use less if not be displayed all of the contents of the files in the terminal
-    #
-    #if [ -n "${exist_files}" ] || [ -p /dev/stdin ]; then
-    if [ -p /dev/stdin ]; then
-        if (( FileLines > DispLines )) || [ -n "$lflag" ]; then
-            echo "$File" | ${Pager} | cat ${nflag} | ${Less}
-        else
-            echo "$File" | ${Pager} | cat ${nflag}
-        fi
-    else
-        if (( FileLines > DispLines )) || [ -n "$lflag" ]; then
-            for file in "${exist_files[@]}"
-            do
-                ${Pager} "$file"
-            done | cat ${nflag} | ${Less}
-        else
-            for file in "${exist_files[@]}"
-            do
-                ${Pager} "$file"
-            done | cat ${nflag}
-        fi
-    fi
-
-    # In case of files that do not exist
-    for file in "${non_exist_files[@]}"
-    do
-        ERR=1
-        echo "$file: no such file or directory"
-    done
-
-    if [ -n "$ERR" ]; then
-        return 1
-    fi
-    return 0
+    local prompt=' -P ?f%f:(stdin). ?lb%lb?L/%L.. [?eEOF:?pb%pb\%:%B..]'
+    LESS="-R -i -f -X $l_flag $n_flag $prompt"
+    export LESS
 }
 
-richpager "$@"
+main()
+{
+    # Analyze the arguments
+    args "$@" || return 1
+
+    if [ -p /dev/stdin ]; then
+        # Put a color to the standard input
+        eval "${highlighter}" | less
+    else
+        if ((argc == 1)); then
+            # When invoked with exactly one argument,
+            # do not read the standard input;
+            # interpret the argument as a file that has been given to the less
+            less "${existent_files[0]}"
+        else
+            # If there are multiple arguments,
+            # run for loop or less -e
+            # to adapting the syntax highlighting to all files
+            if [[ $m_option -eq 1 ]]; then
+                less -eM "${existent_files[@]}"
+            else
+                local f
+                for f in "${existent_files[@]}"
+                do
+                    eval "${highlighter} $f &"
+                done | less
+            fi
+        fi
+    fi
+
+    # If a file that does not exist is given,
+    # raised error
+    local file error
+    for file in "${non_existent_files[@]}"
+    do
+        error=1
+        echo "error: $file: no such file or directory" 1>&2
+    done
+
+    if [[ "$error" == 1 ]]; then
+        return 1
+    fi
+}
+
+main "$@"
